# Generated by Django 5.2.1 on 2025-06-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbracket',
            name='size',
            field=models.IntegerField(choices=[(4, '4 Participants'), (8, '8 Participants'), (16, '16 Participants'), (32, '32 Participants')], default=8),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
