# Generated by Django 5.2.1 on 2025-06-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bracket_creator', '0004_tournamentbracket_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='completed',
        ),
    ]
