# Generated by Django 5.2.1 on 2025-06-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket_creator', '0003_alter_participant_options_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbracket',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentbracket',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
